### ISSUE TITLE
Allow configuration of gRPC maximum message sizes

### ISSUE THREAD

**Issue by alexsomesan** [hashicorp/terraform-plugin-go#106]
### terraform-plugin-go version

```
v0.3.0
```

### Use cases

The Kubernetes manifest provider has to deal with some potentially huge resource configurations. Particularly, the CRD objects of the  Strimzi project (Apache Kafka on K8s) are as big as 16K (10^3) lines of HCL.

Because of this, it can run into the gRPC message limits quite easily. This is most likely to happen in the `UpgradeResourceState` call first, because the previous state payload is transported in raw JSON for this call which is more verbose than the msgpack payload of other protocol calls.

An instance of this happening would look like this to the user:
```
│ Error: Plugin error
│
│   with kubernetes_manifest.customresourcedefinition_kafkas_kafka_strimzi_io,
│   on crds.tf line 1, in resource "kubernetes_manifest" "customresourcedefinition_kafkas_kafka_strimzi_io":
│    1: resource "kubernetes_manifest" "customresourcedefinition_kafkas_kafka_strimzi_io" {
│
│ The plugin returned an unexpected error from plugin.(*GRPCProvider).UpgradeResourceState: rpc error: code = ResourceExhausted desc = grpc: received message larger than max
│ (4528743 vs. 4194304)

```

### Attempted solutions

I have successfully worked around this issue by maxxing out the message size limits on the gRPC server that terraform-plugin-go instantiates. However, this would require us to consume terraform-plugin-go from a fork and constantly rebase on new releases. This would not be ideal. 

The changes I had to make are available here: https://github.com/alexsomesan/terraform-plugin-go/commit/6f9312ae6c69feb8536cdc7df7057038a3ca32ec

### Proposal

We would prefer for this mechanism be exposed to consumers of terraform-plugin-go so that we can configure practical limits as they are needed.

**Comment by paddycarver** [comment]
I think if we're going to bump gRPC request size limits, @hashicorp/terraform-core should at the very least be involved in the discussion, because we may have some unintended consequences for that.

My other concern is if we do this, it will impact ~every provider that upgrades the SDK version, because this will change SDKv2, too.

References:

* hashicorp/terraform#20906
* hashicorp/terraform#20879
* hashicorp/terraform#28305
* hashicorp/terraform#21709
* hashicorp/terraform#24240
* hashicorp/terraform-plugin-sdk#650

**Comment by jbardin** [comment]
This might be an OK solution for now, though if providers start regularly passing very large values around, we are definitely going to run into other issues. A new remote storage interface will definitely need to be streaming, but there's no chance of changing the provider interface in the near future. Since our grpc servers are only exposed locally, they are not protecting themselves from anything other than the terraform client, so there is no real attack vector to exploit this change. 

My initial concern is that removes some of the protection we have from users putting unreasonably large values into their config. Granted the UX there is not very good, because they get a panic rather than an error indicating that a 16MB `user_data` file is really not a good idea.

**Comment by apparentlymart** [comment]
One specific thing I think we'd need to contend with is how this would interact with older Terraform versions that _don't_ offer this capability. We might perhaps need some kinda of reverse-capbility-detection handshake where Terraform Core announces to the provider that it supports this feature and the provider can then refuse to configure with an error message if it wants to require a Terraform Core version which supports this feature.

While we can fiddle with the specific limits here, this also seems like a prompt to reconsider some of our architecture assumptions. In particular, we generally assume that individual resource instance objects are relatively small and that assumption plays out in various different ways, including but not limited to:
* The provider protocol, as we're discussing here.
* The algorithms we use for processing data in memory for the Terraform language runtime, where we've previously seen noticeably poor performance for unusually large objects.
* The way we serialize everything all together in one giant JSON blob for state storage and then expect to be able to stash that resulting blob in typical blob stores, which each have their own practical size limits.

This is not to say that we can't do something more tactical in the meantime to address an immediate problem, but I share @jbardin's concerns that raising this fixed limit is likely to just expose other limits, whether they also be fixed limits (like the state backend blob size limits) or _effective_ limits (noticeably slow performance processing the resulting objects). It seems like we owe ourselves a discussion about whether our current design assumptions are valid and, if not, what new design assumptions _are_ valid. (I don't think there's any world in which we can have _no limits at all_, because we are constrained by various practical concerns, but we could choose limits that better match the problems we're intending to solve.)

**Comment by jbardin** [comment]
Unlike the (experimental) call size optional we use for the GetSchema call, this is only a server-side option, so older versions of Terraform would be effected just the same as current versions. As Alex has shown, this change can technically be done successfully without Terraform's involvement at all, though all the other points still stand.

**Comment by Eric-Jckson** [comment]
I'm getting a similar error when trying to use the Terraform Provider Panos.

`│ The plugin returned an unexpected error from
│ plugin.(*GRPCProvider).PlanResourceChange: rpc error: code =
│ ResourceExhausted desc = grpc: received message larger than max (4460288
│ vs. 4194304)`

The provider allows us to automate the creation of firewall rules. We have a large amount of rules that we are hitting the GRPC error. Since the change for increasing the limit is still being discussed does a workaround currently exist?

@apparentlymart @jbardin thanks!
