### ISSUE TITLE
Handle type aliases in As

### ISSUE THREAD

**Issue by paddycarver** [hashicorp/terraform-plugin-go#22]
"Aliases" (not real aliases, not `type Type2 = Type1`, but `type Type2 Type1`) are handled transparently in cty using the reflect package. See zclconf/go-cty#18 for more details. We could, in theory, support this in As. Should we? Is it worth the added complexity? We've managed to avoid reflect for the most part so far, and I kind of like that simplicity. Things start getting hard to reason about as soon as reflect is introduced. But I could be convinced that

* This is an important feature to include
* This _must_ be included at this level and cannot be done with a helper or at a higher level of abstraction

**Comment by bflad** [comment]
Hello, old friend! I think since there has been no 👍 or commentary on this feature request in three years (I'm guessing since most folks rely on terraform-plugin-sdk/terraform-plugin-framework abstractions) and as you mention would introduce complexity, we are going to close it. If someone has a specific use case for this, they can raise a fresh feature request describing the need.
