### ISSUE TITLE
Evaluate well-known errors for compatibility posture

### ISSUE THREAD

**Issue by paddycarver** [hashicorp/terraform-plugin-go#4]
Our well-known errors, like `ErrUnsupportedDataSource`, are currently set as error values, not types. We may want to evaluate making them less well-known, or returning `fmt.Errorf` wrapped versions, to force people to use `errors.As` instead of doing equality comparisons. This would give us a more flexible posture for future changes than we currently have.

**Comment by bflad** [comment]
Apparently `ErrUnsupportedDataSource` disappeared at some point, but while there are other errors that could use this treatment, I'm not sure there's necessarily been a strong standalone need to introduce breaking changes for this since the API has been fairly stable. I think the best thing to do with this for now is to close this but always keep this consideration in mind for future changes. 👍
