### ISSUE TITLE
Investigate diagnostics helper package

### ISSUE THREAD

**Issue by paddycarver** [hashicorp/terraform-plugin-go#5]
Constructing diagnostics by hand is a bit annoying at the moment. Is it worth shipping a helper package for diagnostics with terraform-plugin-go, or should we keep that in terraform-plugin-sdk where it's easier for us to version it and make breaking changes?

**Comment by bflad** [comment]
I think we've both settled on terraform-plugin-go serving more as a gRPC-Go binding layer than adding too much more to the protocol layer types here, since as you mention the versioning gets harder. Both terraform-plugin-sdk and terraform-plugin-framework have bespoke diagnostics handling packages. It is easy enough to `type diagnostics []*tfprotov6.Diagnostic` outside this module and use that type alias to get higher level functionality.

If there are specific things folks _think_ make sense for this layer, then let's discuss in a specific new issue. 👍
