### ISSUE TITLE
Initial Terraform Plugin Protocol Version 6 (tfprotov6) Implementation

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-plugin-go#65]
### terraform-plugin-go version

```
0.2.1
```

### Use cases

As part of the upcoming Terraform CLI version 0.15 release, a newer version 6 of the Terraform Plugin Protocol is now available. This protocol bump includes goodies such as `NestedType` that will benefit the future of plugin development.

### Proposal

Begin porting over the existing `tfprotov5` directory into a new `tfprotov6` directory and perform the protocol additions. If there is any decision making that needs to be made regarding the implementation details, coalesce them onto this issue.

(I don't mind starting this work at some point in the near future as this directly impacts a project I am working on.)

### References

- https://github.com/hashicorp/terraform/pull/27699
- https://github.com/hashicorp/terraform/pull/27826

**Comment by paddycarver** [comment]
I think we have some ongoing conversations about this with @mildwonkey and it's on our radar.

I currently have the following questions. This is not a complete or exhaustive list:

* Should terraform-plugin-sdk get bumped to protocol 6 or remain at protocol 5?
* Should we be able to mux between protocol 5 and protocol 6 providers?
* Should each protocol version have its own tftypes implementation, or should tftypes be a top-level package that every protocol version depends on?

I don't know that any of these questions has a straightforward answer, and I think all of them will require some discussion because of the implications and nuance.

**Comment by paddycarver** [comment]
#71 has been merged, so I'm going to close this out. I've opened hashicorp/terraform-plugin-sdk#737 to track the SDK impacts of this, and hashicorp/terraform-plugin-mux#19 to track next steps on those repos, but as far as this repo is concerned, it's "done".
